name: Build Next js Application
repoFullName: my-first-gitty-my-first-gitty/circleci
'on':
  push:
    branches:
      - CircleCI
jobs:
  run-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.17.0
    steps:
      - uses: actions/checkout@v3
        name: Setup jobs
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        name: Setup environment
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: git pull origin CircleCI && npm install --global yarn && yarn

      - name: Building
        run: yarn run build


